--
-- PostgreSQL database dump - ORDENADO POR DEPENDENCIAS
--

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- TABLAS BASE (Sin dependencias)
--

-- 1. rol
CREATE TABLE public.rol (
    id_rol integer NOT NULL,
    nombre_rol character varying(50) NOT NULL,
    descripcion character varying(200),
    activo boolean DEFAULT true
);

ALTER TABLE public.rol OWNER TO postgres;

ALTER TABLE public.rol ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 2. usuario
CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    cedula character varying(20) NOT NULL,
    correo character varying(100) NOT NULL,
    telefono character varying(20),
    activo boolean DEFAULT true,
    contrasena character varying(255),
    email_verificado boolean DEFAULT false,
    codigo_verificacion character varying(100),
    fecha_codigo_verificacion timestamp with time zone,
    codigo_recuperacion character varying(100),
    session_token text,
    session_token_app text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT usuario_cedula_key UNIQUE (cedula),
    CONSTRAINT usuario_correo_key UNIQUE (correo)
);

ALTER TABLE public.usuario OWNER TO postgres;

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 3. carrera
CREATE TABLE public.carrera (
    id_carrera integer NOT NULL,
    nombre_carrera character varying(100) NOT NULL,
    activo boolean DEFAULT true
);

ALTER TABLE public.carrera OWNER TO postgres;

ALTER TABLE public.carrera ALTER COLUMN id_carrera ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrera_id_carrera_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 4. periodo
CREATE TABLE public.periodo (
    id_periodo integer NOT NULL,
    nombre_periodo character varying(20) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    activo boolean DEFAULT true
);

ALTER TABLE public.periodo OWNER TO postgres;

ALTER TABLE public.periodo ALTER COLUMN id_periodo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.periodo_id_periodo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TABLAS QUE DEPENDEN DE LAS BASES
--

-- 5. usuario_rol (Depende de: usuario, rol)
CREATE TABLE public.usuario_rol (
    id_usuario_rol integer NOT NULL,
    id_usuario integer NOT NULL,
    id_rol integer NOT NULL,
    fecha_desde date NOT NULL,
    fecha_hasta date,
    activo boolean DEFAULT true
);

ALTER TABLE public.usuario_rol OWNER TO postgres;

ALTER TABLE public.usuario_rol ALTER COLUMN id_usuario_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_rol_id_usuario_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 6. profesor (Depende de: usuario_rol)
CREATE TABLE public.profesor (
    id_profesor integer NOT NULL,
    id_usuario_rol integer NOT NULL,
    fecha_ingreso date NOT NULL,
    activo boolean DEFAULT true
);

ALTER TABLE public.profesor OWNER TO postgres;

ALTER TABLE public.profesor ALTER COLUMN id_profesor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profesor_id_profesor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 7. profesor_carrera (Depende de: profesor, carrera)
CREATE TABLE public.profesor_carrera (
    id_profesor_carrera integer NOT NULL,
    id_profesor integer NOT NULL,
    id_carrera integer NOT NULL,
    dedicacion character varying(20) NOT NULL,
    fecha_desde date NOT NULL,
    fecha_hasta date,
    activo boolean DEFAULT true
);

ALTER TABLE public.profesor_carrera OWNER TO postgres;

ALTER TABLE public.profesor_carrera ALTER COLUMN id_profesor_carrera ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profesor_carrera_id_profesor_carrera_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 8. coordinador (Depende de: usuario_rol, carrera)
CREATE TABLE public.coordinador (
    id_coordinador integer NOT NULL,
    id_usuario_rol integer NOT NULL,
    id_carrera integer NOT NULL,
    fecha_desde date NOT NULL,
    fecha_hasta date,
    activo boolean DEFAULT true
);

ALTER TABLE public.coordinador OWNER TO postgres;

ALTER TABLE public.coordinador ALTER COLUMN id_coordinador ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coordinador_id_coordinador_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 9. asignatura (Depende de: carrera)
CREATE TABLE public.asignatura (
    id_asignatura integer NOT NULL,
    id_carrera integer NOT NULL,
    nombre_asignatura character varying(100) NOT NULL,
    creditos integer DEFAULT 3,
    horas_semanales numeric(4,2),
    activo boolean DEFAULT true
);

ALTER TABLE public.asignatura OWNER TO postgres;

ALTER TABLE public.asignatura ALTER COLUMN id_asignatura ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asignatura_id_asignatura_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 10. asignatura_profesor (Depende de: asignatura, profesor)
CREATE TABLE public.asignatura_profesor (
    id_asignatura_profesor integer NOT NULL,
    id_asignatura integer NOT NULL,
    id_profesor integer NOT NULL,
    fecha_desde date NOT NULL,
    fecha_hasta date,
    activo boolean DEFAULT true
);

ALTER TABLE public.asignatura_profesor OWNER TO postgres;

ALTER TABLE public.asignatura_profesor ALTER COLUMN id_asignatura_profesor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asignatura_profesor_id_asignatura_profesor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 11. horario (Depende de: asignatura_profesor)
CREATE TABLE public.horario (
    id_horario integer NOT NULL,
    id_asignatura_profesor integer NOT NULL,
    dia_semana character varying(10) NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    activo boolean DEFAULT true,
    aula character varying(50)
);

ALTER TABLE public.horario OWNER TO postgres;

ALTER TABLE public.horario ALTER COLUMN id_horario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.horario_id_horario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 12. qr (Depende de: coordinador, profesor)
CREATE TABLE public.qr (
    id_qr integer NOT NULL,
    id_coordinador integer,
    codigo_qr character varying(100) NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    activo boolean DEFAULT true,
    descripcion character varying(200),
    id_profesor integer,
    ubicacion character varying(100)
);

ALTER TABLE public.qr OWNER TO postgres;

ALTER TABLE public.qr ALTER COLUMN id_qr ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qr_id_qr_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 13. asistencia (Depende de: profesor, horario, qr, coordinador)
CREATE TABLE public.asistencia (
    id_asistencia integer NOT NULL,
    id_profesor integer NOT NULL,
    id_horario integer,
    id_qr integer NOT NULL,
    id_coordinador integer,
    fecha_entrada timestamp with time zone DEFAULT now() NOT NULL,
    fecha_salida timestamp with time zone,
    CONSTRAINT check_fechas CHECK ((fecha_salida IS NULL OR (fecha_salida >= fecha_entrada)))
);

ALTER TABLE public.asistencia OWNER TO postgres;

ALTER TABLE public.asistencia ALTER COLUMN id_asistencia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asistencia_id_asistencia_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 14. justificativo (Depende de: asistencia)
CREATE TABLE public.justificativo (
    id_justificativo integer NOT NULL,
    id_asistencia integer NOT NULL,
    motivo character varying(200) NOT NULL,
    estado character varying(20) NOT NULL,
    documento_url character varying(500),
    fecha_solicitud timestamp with time zone DEFAULT now(),
    fecha_respuesta timestamp with time zone,
    observaciones_coordinador text
);

ALTER TABLE public.justificativo OWNER TO postgres;

ALTER TABLE public.justificativo ALTER COLUMN id_justificativo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.justificativo_id_justificativo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- 15. horas (Depende de: profesor_carrera, periodo)
CREATE TABLE public.horas (
    id_horas integer NOT NULL,
    id_profesor_carrera integer NOT NULL,
    id_periodo integer NOT NULL,
    horas_contratadas numeric(5,2) NOT NULL,
    horas_dictadas numeric(5,2) DEFAULT 0,
    horas_justificadas numeric(5,2) DEFAULT 0,
    horas_restantes numeric(5,2) NOT NULL,
    observaciones character varying(200)
);

ALTER TABLE public.horas OWNER TO postgres;

ALTER TABLE public.horas ALTER COLUMN id_horas ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.horas_id_horas_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- PRIMARY KEYS
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id_rol);

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);

ALTER TABLE ONLY public.carrera
    ADD CONSTRAINT carrera_pkey PRIMARY KEY (id_carrera);

ALTER TABLE ONLY public.periodo
    ADD CONSTRAINT periodo_pkey PRIMARY KEY (id_periodo);

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_pkey PRIMARY KEY (id_usuario_rol);

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT profesor_pkey PRIMARY KEY (id_profesor);

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT profesor_id_usuario_rol_key UNIQUE (id_usuario_rol);

ALTER TABLE ONLY public.profesor_carrera
    ADD CONSTRAINT profesor_carrera_pkey PRIMARY KEY (id_profesor_carrera);

ALTER TABLE ONLY public.coordinador
    ADD CONSTRAINT coordinador_pkey PRIMARY KEY (id_coordinador);

ALTER TABLE ONLY public.coordinador
    ADD CONSTRAINT coordinador_id_usuario_rol_key UNIQUE (id_usuario_rol);

ALTER TABLE ONLY public.asignatura
    ADD CONSTRAINT asignatura_pkey PRIMARY KEY (id_asignatura);

ALTER TABLE ONLY public.asignatura_profesor
    ADD CONSTRAINT asignatura_profesor_pkey PRIMARY KEY (id_asignatura_profesor);

ALTER TABLE ONLY public.horario
    ADD CONSTRAINT horario_pkey PRIMARY KEY (id_horario);

ALTER TABLE ONLY public.qr
    ADD CONSTRAINT qr_pkey PRIMARY KEY (id_qr);

ALTER TABLE ONLY public.qr
    ADD CONSTRAINT qr_codigo_qr_key UNIQUE (codigo_qr);

ALTER TABLE ONLY public.asistencia
    ADD CONSTRAINT asistencia_pkey PRIMARY KEY (id_asistencia);

ALTER TABLE ONLY public.justificativo
    ADD CONSTRAINT justificativo_pkey PRIMARY KEY (id_justificativo);

ALTER TABLE ONLY public.horas
    ADD CONSTRAINT horas_pkey PRIMARY KEY (id_horas);

--
-- FOREIGN KEYS
--

-- usuario_rol
ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_id_rol_fkey FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol) ON DELETE CASCADE;

-- profesor
ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT profesor_id_usuario_rol_fkey FOREIGN KEY (id_usuario_rol) REFERENCES public.usuario_rol(id_usuario_rol) ON DELETE CASCADE;

-- profesor_carrera
ALTER TABLE ONLY public.profesor_carrera
    ADD CONSTRAINT profesor_carrera_id_profesor_fkey FOREIGN KEY (id_profesor) REFERENCES public.profesor(id_profesor) ON DELETE CASCADE;

ALTER TABLE ONLY public.profesor_carrera
    ADD CONSTRAINT profesor_carrera_id_carrera_fkey FOREIGN KEY (id_carrera) REFERENCES public.carrera(id_carrera) ON DELETE CASCADE;

-- coordinador
ALTER TABLE ONLY public.coordinador
    ADD CONSTRAINT coordinador_id_usuario_rol_fkey FOREIGN KEY (id_usuario_rol) REFERENCES public.usuario_rol(id_usuario_rol) ON DELETE CASCADE;

ALTER TABLE ONLY public.coordinador
    ADD CONSTRAINT coordinador_id_carrera_fkey FOREIGN KEY (id_carrera) REFERENCES public.carrera(id_carrera) ON DELETE CASCADE;

-- asignatura
ALTER TABLE ONLY public.asignatura
    ADD CONSTRAINT asignatura_id_carrera_fkey FOREIGN KEY (id_carrera) REFERENCES public.carrera(id_carrera) ON DELETE CASCADE;

-- asignatura_profesor
ALTER TABLE ONLY public.asignatura_profesor
    ADD CONSTRAINT asignatura_profesor_id_asignatura_fkey FOREIGN KEY (id_asignatura) REFERENCES public.asignatura(id_asignatura) ON DELETE CASCADE;

ALTER TABLE ONLY public.asignatura_profesor
    ADD CONSTRAINT asignatura_profesor_id_profesor_fkey FOREIGN KEY (id_profesor) REFERENCES public.profesor(id_profesor) ON DELETE CASCADE;

-- horario
ALTER TABLE ONLY public.horario
    ADD CONSTRAINT horario_id_asignatura_profesor_fkey FOREIGN KEY (id_asignatura_profesor) REFERENCES public.asignatura_profesor(id_asignatura_profesor) ON DELETE CASCADE;

-- qr
ALTER TABLE ONLY public.qr
    ADD CONSTRAINT qr_id_coordinador_fkey FOREIGN KEY (id_coordinador) REFERENCES public.coordinador(id_coordinador) ON DELETE CASCADE;

ALTER TABLE ONLY public.qr
    ADD CONSTRAINT qr_id_profesor_fkey FOREIGN KEY (id_profesor) REFERENCES public.profesor(id_profesor) ON DELETE CASCADE;

-- asistencia
ALTER TABLE ONLY public.asistencia
    ADD CONSTRAINT asistencia_id_profesor_fkey FOREIGN KEY (id_profesor) REFERENCES public.profesor(id_profesor) ON DELETE CASCADE;

ALTER TABLE ONLY public.asistencia
    ADD CONSTRAINT asistencia_id_horario_fkey FOREIGN KEY (id_horario) REFERENCES public.horario(id_horario) ON DELETE CASCADE;

ALTER TABLE ONLY public.asistencia
    ADD CONSTRAINT asistencia_id_qr_fkey FOREIGN KEY (id_qr) REFERENCES public.qr(id_qr) ON DELETE CASCADE;

-- justificativo
ALTER TABLE ONLY public.justificativo
    ADD CONSTRAINT justificativo_id_asistencia_fkey FOREIGN KEY (id_asistencia) REFERENCES public.asistencia(id_asistencia) ON DELETE CASCADE;

-- horas
ALTER TABLE ONLY public.horas
    ADD CONSTRAINT horas_id_profesor_carrera_fkey FOREIGN KEY (id_profesor_carrera) REFERENCES public.profesor_carrera(id_profesor_carrera) ON DELETE CASCADE;

ALTER TABLE ONLY public.horas
    ADD CONSTRAINT horas_id_periodo_fkey FOREIGN KEY (id_periodo) REFERENCES public.periodo(id_periodo) ON DELETE CASCADE;

--
-- INDEXES
--

CREATE INDEX idx_usuario_correo ON public.usuario USING btree (correo);
CREATE INDEX idx_usuario_rol_id_usuario ON public.usuario_rol USING btree (id_usuario);
CREATE INDEX idx_usuario_rol_id_rol ON public.usuario_rol USING btree (id_rol);
CREATE INDEX idx_profesor_id_usuario_rol ON public.profesor USING btree (id_usuario_rol);
CREATE INDEX idx_profesor_carrera_id_profesor ON public.profesor_carrera USING btree (id_profesor);
CREATE INDEX idx_profesor_carrera_id_carrera ON public.profesor_carrera USING btree (id_carrera);
CREATE INDEX idx_coordinador_id_usuario_rol ON public.coordinador USING btree (id_usuario_rol);
CREATE INDEX idx_coordinador_id_carrera ON public.coordinador USING btree (id_carrera);
CREATE INDEX idx_asignatura_id_carrera ON public.asignatura USING btree (id_carrera);
CREATE INDEX idx_asignatura_profesor_id_asignatura ON public.asignatura_profesor USING btree (id_asignatura);
CREATE INDEX idx_asignatura_profesor_id_profesor ON public.asignatura_profesor USING btree (id_profesor);
CREATE INDEX idx_horario_id_asignatura_profesor ON public.horario USING btree (id_asignatura_profesor);
CREATE INDEX idx_qr_id_coordinador ON public.qr USING btree (id_coordinador);
CREATE INDEX idx_qr_id_profesor ON public.qr USING btree (id_profesor);
CREATE INDEX idx_asistencia_id_profesor ON public.asistencia USING btree (id_profesor);
CREATE INDEX idx_asistencia_id_horario ON public.asistencia USING btree (id_horario);
CREATE INDEX idx_asistencia_id_qr ON public.asistencia USING btree (id_qr);
CREATE INDEX idx_justificativo_id_asistencia ON public.justificativo USING btree (id_asistencia);
CREATE INDEX idx_horas_id_profesor_carrera ON public.horas USING btree (id_profesor_carrera);
CREATE INDEX idx_horas_id_periodo ON public.horas USING btree (id_periodo);

--
-- PostgreSQL database dump complete
--
